name 'jenkins-wrapper'
maintainer 'flugel.it'
maintainer_email 'infradevs@flugel.it'
license 'MIT License'
description 'Installs/Configures jenkins server'
long_description 'Installs/Configures jenkins server'
version '0.2.1'

depends 'java'
depends 'git'
depends 'jenkins'
depends 'poise-python'
